<?php if (!defined('BASEPATH'))
    exit('No direct script access allowed');
/*
<!-- .................................. -->
<!-- ...........COPYRIGHT ............. -->
<!-- Authors : Hisyam Husein .......... -->
<!-- Email : hisyam.husein@gmail.com .. -->
<!-- About : hisyam.ismul.com ......... -->
<!-- Instagram : @hisyambsa............ -->
<!-- .................................. -->
*/
class Digitalisasi_form_k31_model extends CI_Model
{

    public $table = 'digitalisasi_form_k31';
    public $id = 'id_digitalisasi_form_k31';
    public $delete_at = 'delete_at_digitalisasi_form_k31';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all($kondisi = NULL)
    {
        if ($kondisi != NULL) {
            $i = 0;
            foreach ($kondisi as $item) // loop column 
            {
                if ($i === 0) // first loop
                {
                    $this->db->group_start(); // open bracket.
                    $this->db->where($kondisi); // looping where
                }
                if (count($kondisi) - 1 == $i) { //last loop
                    $this->db->group_end(); //close bracket
                }
                $i++;
            }
        }
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    // get all
    function get_all_join($kondisi = NULL, $db_or_where = false, $k1 = false)
    {
        if ($kondisi != NULL) {
            $i = 0;
            foreach ($kondisi as $item) // loop column 
            {
                if ($i === 0) // first loop
                {
                    $this->db->group_start(); // open bracket.
                    if ($db_or_where == false) {
                        $this->db->where($kondisi); // looping where
                    } else {
                        $this->db->or_where($kondisi); // looping where
                    }
                }
                if (count($kondisi) - 1 == $i) { //last loop
                    $this->db->group_end(); //close bracket
                }
                $i++;
            }
        }
        $this->db->order_by($this->id, $this->order);
        $this->db->join('digitalisasi_form_k31', 'digitalisasi_form_k31.nomor_k32_digitalisasi_form_k31 = digitalisasi_form_k32.nomor_digitalisasi_form_k32');
        $this->db->join('digitalisasi_form_k1 as lumpsum', 'lumpsum.nomor_digitalisasi_form_k1 = digitalisasi_form_k31.nomor_lumpsum_k1_digitalisasi_form_k31');
        if ($k1) {
            $this->db->join('digitalisasi_form_k1 as uang_muka', 'uang_muka.nomor_digitalisasi_form_k1 = digitalisasi_form_k31.nomor_uang_muka_k1_digitalisasi_form_k31');
        }

        return $this->db->get($this->table)->result();
    }
    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $kondisi = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        if ($kondisi != NULL) {
            $i = 0;
            foreach ($kondisi as $item) // loop column 
            {
                if ($i === 0) // first loop
                {
                    $this->db->group_start(); // open bracket.
                    $this->db->where($kondisi); // looping where
                }
                if (count($kondisi) - 1 == $i) { //last loop
                    $this->db->group_end(); //close bracket
                }
                $i++;
            }
        } else {
        }
        $this->db->limit($limit, $start);

        $this->db->where($this->delete_at, NULL);
        return $this->db->get($this->table)->result();
    }
    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return ($this->db->affected_rows() != 1) ? false : true;
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
        return ($this->db->affected_rows() != 1) ? false : true;
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
        return ($this->db->affected_rows() != 1) ? false : true;
    }
}

/* End of file Digitalisasi_form_k31_model.php */
/* Location: ./application/models/Digitalisasi_form_k31_model.php */
/* Please DO NOT modify this information : */
/* Generated by Hisyam 2020-07-23 02:47:46 */
/* http://hisyam.ismul.com.com */