<?php if (!defined('BASEPATH'))
    exit('No direct script access allowed');
/*
<!-- .................................. -->
<!-- ...........COPYRIGHT ............. -->
<!-- Authors : Hisyam Husein .......... -->
<!-- Email : hisyam.husein@gmail.com .. -->
<!-- About : hisyam.ismul.com ......... -->
<!-- Instagram : @hisyambsa............ -->
<!-- .................................. -->
*/
class Hasil_suhu_gt_covid_model extends CI_Model
{

    public $table = 'hasil_suhu_gt_covid';
    public $id = 'id_hasil_suhu_gt_covid';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all($kondisi = NULL)
    {
        if ($kondisi != NULL) {
            $i = 0;
            foreach ($kondisi as $item) // loop column 
            {
                if ($i === 0) // first loop
                {
                    $this->db->group_start(); // open bracket.
                    $this->db->where($kondisi); // looping where
                }
                if (count($kondisi) - 1 == $i) { //last loop
                    $this->db->group_end(); //close bracket
                }
                $i++;
            }
        }
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function cek_tanggal_suhu($nama = '')
    {
        $cek_nama_tanggal = $this->db->order_by($this->id, $this->order)
            ->limit(1)
            ->where('nama_hasil_suhu_gt_covid', $nama)
            ->where('tanggal_hasil_suhu_gt_covid', date('Y-m-d'))
            ->get($this->table)
            ->row();
        return $cek_nama_tanggal;
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return ($this->db->affected_rows() != 1) ? false : true;
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
        return ($this->db->affected_rows() != 1) ? false : true;
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
        return ($this->db->affected_rows() != 1) ? false : true;
    }
}

/* End of file Hasil_suhu_gt_covid_model.php */
/* Location: ./application/models/Hasil_suhu_gt_covid_model.php */
/* Please DO NOT modify this information : */
/* Generated by Hisyam 2020-06-09 12:20:48 */
/* http://hisyam.ismul.com.com */