<?php if (!defined('BASEPATH'))
	exit('No direct script access allowed');
/*
<!-- .................................. -->
<!-- ...........COPYRIGHT ............. -->
<!-- Authors : Hisyam Husein .......... -->
<!-- Email : hisyam.husein@gmail.com .. -->
<!-- About : hisyam.ismul.com ......... -->
<!-- Instagram : @hisyambsa............ -->
<!-- .................................. -->
*/
class Hasil_mingguan_survey_gt_covid_model extends CI_Model
{

	public $table = 'hasil_mingguan_survey_gt_covid';
	public $id = 'id_hasil_mingguan_survey_gt_covid';
	public $order = 'DESC';

	function __construct()
	{
		parent::__construct();
	}
	function data_user_belum_survey($not = 'NOT')
	{
		$query = $this->db->query("SELECT users.unit_kerja, users.first_name, users.job_level, users.region from users WHERE users.region !='admin' AND users.active =1 and users.nip $not IN(SELECT hasil_mingguan_survey_gt_covid.nip_mingguan_survey_gt_covid FROM hasil_mingguan_survey_gt_covid WHERE hasil_mingguan_survey_gt_covid.tanggal_mingguan_survey_gt_covid = CURRENT_DATE)  ORDER by unit_kerja, region, first_name");
		return $query->result();
	}
	function data_user_belum_survey_by_unit_kerja($unit_kerja, $not = 'NOT')
	{
		$query = $this->db->query("SELECT users.unit_kerja, users.first_name, users.job_level, users.region from users WHERE users.unit_kerja = '$unit_kerja' AND users.region !='admin' AND users.active =1 and users.nip $not IN(SELECT hasil_mingguan_survey_gt_covid.nip_mingguan_survey_gt_covid FROM hasil_mingguan_survey_gt_covid WHERE  hasil_mingguan_survey_gt_covid.tanggal_mingguan_survey_gt_covid = CURRENT_DATE)  ORDER by unit_kerja, region, first_name");
		// var_dump("SELECT users.unit_kerja, users.first_name, users.region from users WHERE users.unit_kerja = '$unit_kerja' AND users.region !='admin' AND users.active =1 and users.nip NOT IN(SELECT hasil_survey_gt_covid.nip_survey_gt_covid FROM hasil_survey_gt_covid WHERE  hasil_survey_gt_covid.tanggal_survey_gt_covid = CURRENT_DATE)  ORDER by unit_kerja, region, first_name");
		return $query->result();
	}
	// get all
	function get_all($kondisi = NULL)
	{
		if ($kondisi != NULL) {
			$i = 0;
			foreach ($kondisi as $item) // loop column 
			{
				if ($i === 0) // first loop
				{
					$this->db->group_start(); // open bracket.
					$this->db->where($kondisi); // looping where
				}
				if (count($kondisi) - 1 == $i) { //last loop
					$this->db->group_end(); //close bracket
				}
				$i++;
			}
		}
		$this->db->order_by($this->id, $this->order);
		return $this->db->get($this->table)->result();
	}

	// get data by id
	function get_by_id($id)
	{
		$this->db->where($this->id, $id);
		return $this->db->get($this->table)->row();
	}

	function cek_nip_tanggal($nip = '')
	{
		$cek_nip_tanggal = $this->db->order_by($this->id, $this->order)
			->limit(1)
			->where('nip_mingguan_survey_gt_covid', $nip)
			->where('tanggal_mingguan_survey_gt_covid', date('Y-m-d'))
			->get($this->table)
			->row();
		return $cek_nip_tanggal;
	}
	// insert data
	function insert($data)
	{
		$this->db->insert($this->table, $data);
		return ($this->db->affected_rows() != 1) ? false : true;
	}

	// update data
	function update($id, $data)
	{
		$this->db->where($this->id, $id);
		$this->db->update($this->table, $data);
		return ($this->db->affected_rows() != 1) ? false : true;
	}

	// delete data
	function delete($id)
	{
		$this->db->where($this->id, $id);
		$this->db->delete($this->table);
		return ($this->db->affected_rows() != 1) ? false : true;
	}
}

/* End of file Hasil_mingguan_survey_gt_covid_model.php */
/* Location: ./application/models/Hasil_mingguan_survey_gt_covid_model.php */
/* Please DO NOT modify this information : */
/* Generated by Hisyam 2020-04-10 05:37:23 */
/* http://hisyam.ismul.com.com */
