<?php if (!defined('BASEPATH'))
    exit('No direct script access allowed');
/*
<!-- .................................. -->
<!-- ...........COPYRIGHT ............. -->
<!-- Authors : Hisyam Husein .......... -->
<!-- Email : hisyam.husein@gmail.com .. -->
<!-- About : hisyam.ismul.com ......... -->
<!-- Instagram : @hisyambsa............ -->
<!-- .................................. -->
*/
class Karyawan_struktur_model extends CI_Model
{

    public $table = 'karyawan_struktur';
    public $id = 'id_karyawan_struktur';
    public $order = 'asc';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all($kondisi = NULL)
    {
        if ($kondisi != NULL) {
            $i = 0;
            foreach ($kondisi as $item) // loop column 
            {
                if ($i === 0) // first loop
                {
                    $this->db->group_start(); // open bracket.
                    $this->db->where($kondisi); // looping where
                }
                if (count($kondisi) - 1 == $i) { //last loop
                    $this->db->group_end(); //close bracket
                }
                $i++;
            }
        }
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data with limit and search
    function get_limit_data_join_level($limit, $start = 0, $q = NULL)
    {
        $this->db->join('setup_level_struktur', 'setup_level_struktur.id_setup_level_struktur = karyawan_struktur.karyawan_level_struktur', 'left');

        $this->db->order_by('id_karyawan_struktur', 'ASC');
        $this->db->like('id_karyawan_struktur', $q);
        $this->db->or_like('nip_karyawan_struktur', $q);
        $this->db->or_like('nama_karyawan_struktur', $q);
        $this->db->or_like('nip_atasan_karyawan_struktur', $q);
        $this->db->or_like('nama_atasan_karyawan_struktur', $q);
        $this->db->or_like('karyawan_level_struktur', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return ($this->db->affected_rows() != 1) ? false : true;
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
        return ($this->db->affected_rows() != 1) ? false : true;
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
        return ($this->db->affected_rows() != 1) ? false : true;
    }
}

/* End of file Karyawan_struktur_model.php */
/* Location: ./application/models/Karyawan_struktur_model.php */
/* Please DO NOT modify this information : */
/* Generated by Hisyam 2020-06-08 05:41:02 */
/* http://hisyam.ismul.com.com */