<?php if (!defined('BASEPATH'))
    exit('No direct script access allowed');
/*
<!-- .................................. -->
<!-- ...........COPYRIGHT ............. -->
<!-- Authors : Hisyam Husein .......... -->
<!-- Email : hisyam.husein@gmail.com .. -->
<!-- About : hisyam.ismul.com ......... -->
<!-- Instagram : @hisyambsa............ -->
<!-- .................................. -->
*/
class Struktur_organisasi_perjalanan_dinas_model extends CI_Model
{

    public $table = 'struktur_organisasi_perjalanan_dinas';
    public $id = 'id_struktur_organisasi_perjalanan_dinas';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }


    // get all
    function get_all($kondisi = NULL)
    {
        if ($kondisi != NULL) {
            $i = 0;
            foreach ($kondisi as $item) // loop column 
            {
                if ($i === 0) // first loop
                {
                    $this->db->group_start(); // open bracket.
                    $this->db->where($kondisi); // looping where
                }
                if (count($kondisi) - 1 == $i) { //last loop
                    $this->db->group_end(); //close bracket
                }
                $i++;
            }
        }
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id_struktur_organisasi_perjalanan_dinas', $q);
        $this->db->or_like('nama_struktur_organisasi_perjalanan_dinas', $q);
        $this->db->or_like('boss_struktur_organisasi_perjalanan_dinas', $q);
        $this->db->or_like('golongan_struktur_organisasi_perjalanan_dinas', $q);
        $this->db->or_like('jabatan_struktur_organisasi_perjalanan_dinas', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_struktur_organisasi_perjalanan_dinas', $q);
        $this->db->or_like('nama_struktur_organisasi_perjalanan_dinas', $q);
        $this->db->or_like('boss_struktur_organisasi_perjalanan_dinas', $q);
        $this->db->or_like('golongan_struktur_organisasi_perjalanan_dinas', $q);
        $this->db->or_like('jabatan_struktur_organisasi_perjalanan_dinas', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return ($this->db->affected_rows() != 1) ? false : true;
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
        return ($this->db->affected_rows() != 1) ? false : true;
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
        return ($this->db->affected_rows() != 1) ? false : true;
    }
}

/* End of file Struktur_organisasi_perjalanan_dinas_model.php */
/* Location: ./application/models/Struktur_organisasi_perjalanan_dinas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Hisyam 2020-07-29 02:13:38 */
/* http://hisyam.ismul.com.com */