<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Zend\\Stdlib\\' => array($vendorDir . '/zendframework/zend-stdlib/src'),
    'Zend\\ServiceManager\\' => array($vendorDir . '/zendframework/zend-servicemanager/src'),
    'Zend\\Serializer\\' => array($vendorDir . '/zendframework/zend-serializer/src'),
    'Zend\\Json\\' => array($vendorDir . '/zendframework/zend-json/src'),
    'Zend\\Hydrator\\' => array($vendorDir . '/zendframework/zend-hydrator/src'),
    'Zend\\EventManager\\' => array($vendorDir . '/zendframework/zend-eventmanager/src'),
    'Zend\\Db\\' => array($vendorDir . '/zendframework/zend-db/src'),
    'Zend\\Cache\\' => array($vendorDir . '/zendframework/zend-cache/src'),
    'Valitron\\' => array($vendorDir . '/vlucas/valitron/src/Valitron'),
);
